# Generated by Django 4.2.16 on 2026-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('presentation_type', models.CharField(blank=True, choices=[('PROJECT_VIVA', 'Project Viva'), ('RESEARCH_SEMINAR', 'Research Seminar'), ('STARTUP_PITCH', 'Startup Pitch'), ('INTERVIEW_DECK', 'Interview Deck'), ('TUTORIAL', 'Tutorial'), ('INTERNAL_REVIEW', 'Internal Review')], max_length=50)),
                ('audience', models.CharField(blank=True, choices=[('PROFESSOR', 'Professor'), ('HR_RECRUITER', 'HR Recruiter'), ('INVESTOR', 'Investor'), ('STUDENTS', 'Students'), ('ENGINEERS', 'Engineers')], max_length=50)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_content', models.JSONField(blank=True, default=dict)),
                ('slides_data', models.JSONField(blank=True, default=list)),
                ('viva_questions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('ERROR', 'Error')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
